### ISSUE TITLE
Error on every click

### ISSUE THREAD

**Issue by psalaets** [jelmerdemaat/dwnld-attr-polyfill#1]
I added this to my project and I'm seeing errors in the IE11 devtools console for each click I make. The error happens when clicking on elements that aren't links, like a button or a div.

I'm attaching a screenshot of the messages although I don't know how helpful this is -- it's minified code.
![devtools-console-after-three-clicks](https://user-images.githubusercontent.com/123952/70357368-b31bae80-1844-11ea-9c83-eff128bbd567.png)

**Comment by psalaets** [comment]
I looked around a bit and I think the issue is [line 7 and 8](https://github.com/jelmerdemaat/dwnld-attr-polyfill/blob/master/src/download-polyfill.js#L7-L8).

The code is splitting the filename out of the href attribute before it knows that `target` is an `<a>` element. I'm guessing that `href` is `undefined` when it goes to `new URL()`.

**Comment by jelmerdemaat** [comment]
Oh I see, many thanks!  👍  I'll review the PR.

**Comment by jelmerdemaat** [comment]
Fixed looked good. Merged it in! You can update to 1.1.6 :)
