### ISSUE TITLE
Supporting download attribute as file name

### ISSUE THREAD

**Issue by Trolleymusic** [jelmerdemaat/dwnld-attr-polyfill#11]
Hello,

This polyfill uses the last part of the `href` path instead of `download` attribute to set the file name.

I'm having the issue where if I'm using `createObjectURL` to create a Blob URL then the file downloaded is an extensionless uuid. Eg:

```html
<a href="http://example.com/example.pdf" download>Download the PDF</a>
```

works as expected and reproduces the expected behaviour, a file `example.pdf` is downloaded. But:

```html
<!-- example generated blobObjectURL -->
<a href="blob://73d4fa35-081a-474e-aad8-5766240d5da4" download="example.pdf">Download the PDF</a>
```

Does not, on a browser that supports download, a file `example.pdf` is downloaded, but on IE11 an extensionless file `73d4fa35-081a-474e-aad8-5766240d5da4` is downloaded.

I'll open a PR for this, to use the download attribute unless it's empty.

Thank you!

**Comment by jelmerdemaat** [comment]
Fixed! Thanks 👍

**Comment by Trolleymusic** [comment]
@jelmerdemaat when will you publish a new version to NPM?

**Comment by jelmerdemaat** [comment]
@Trolleymusic Just did! Thanks for reminding me :)
