### ISSUE TITLE
IE11 Does not support new URL()

### ISSUE THREAD

**Issue by sebastiansandqvist** [jelmerdemaat/dwnld-attr-polyfill#7]
This polyfill does not work in IE11 unless `URL` is also polyfilled:
See https://caniuse.com/#feat=url and https://developer.mozilla.org/en-US/docs/Web/API/URL

Polyfilling `URL` entirely is overkill for this case, since it is only being used to extract the pathname (and then the filename) from the download url.

I'd propose adding either a small helper function to extract the filename from a url or mentioning in the docs that for IE11 to work out of the box with this polyfill, another polyfill is also required.

**Comment by erikjohnsen6d** [comment]
@sebastiansandqvist I used `target.getAttribute('download')`, which will hash a filename if not present on the `download="name.ext"` attribute.
